os: linux
services:
   - docker
sudo: required
addons:
  postgresql: "9.4"
language: python
env:
  global:
    - CONAN_REFERENCE="libpqxx/5.0.1"
    - CONAN_USERNAME="jgsogo"
    - CONAN_CHANNEL="stable"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_REMOTES="https://api.bintray.com/conan/jgsogo/conan-packages"
    - CONAN_UPLOAD="https://api.bintray.com/conan/jgsogo/conan-packages"

  matrix:
    - CONAN_GCC_VERSIONS=4.8
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_USE_DOCKER=1
matrix:
   include:
       - os: osx
         osx_image: xcode7.3
         language: generic
         env:
       - os: osx
         osx_image: xcode7.1
         language: generic
         env:
       - os: osx
         osx_image: xcode8.1
         language: generic
         env:

install:
  - ./.travis/install.sh

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "\conninfo" -U postgres

script:
  - export PGDATABASE="travis_ci_test"
  - export PGUSER="postgres"
  - export PGPASSWORD=""
  - export PGHOSTADDR="$(/sbin/ip route|awk '/default/ { print $3 }')"
  - sudo echo "listen_addresses = '*'" >> /etc/postgresql/9.4/main/postgresql.conf
  - sudo /etc/init.d/postgresql restart
  - ./.travis/run.sh
